apiVersion: v1
kind: Service
metadata:
  name: jackson-chen-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: jackson-chen-nginxxx
  ports:
  - name: http
    port: 80
    targetPort: 80
