apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jackson-chen-nginx
  name: jackson-chen-nginxxxxxxxx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jackson-chen-nginxxx
  template:
    metadata:
      labels:
        app: jackson-chen-nginxxx
    spec:
      containers:
      - name: jackson-chen-nginxx
        image: nginx
        ports:
        - containerPort: 80
