apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec1
spec:
  containers:
  - name: liveness
    image: wrre/hello-kubernetes-client:v1
    ports:
    - name: jackson
      containerPort: 80
    livenessProbe:
      exec:
        command:
        - cat
        - /app/package.json
      initialDelaySeconds: 5
      periodSeconds: 5
