apiVersion: v1
kind: Service
metadata:
  name: jackson-chen-service
spec:
  ports:
  - port: 3000
    nodePort: 30000
    protocol: TCP
    targetPort: jackson-port
  selector:
    app: jackson
  type: NodePort

