apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jackson-chen-namespace
  name: jackson-chen-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
