apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readpods
  namespace: jackson-chen-namespace
subjects:
  - kind: ServiceAccount
    name: jackson-chen-serviceaccount
    namespace: jackson-chen-namespace
roleRef:
  kind: Role
  name: jackson-chen-role
  apiGroup: rbac.authorization.k8s.io
