apiVersion: v1
kind: Pod
metadata:
  name: sa-example
  namespace: jackson-chen-namespace
spec:
  serviceAccountName: jackson-chen-serviceaccount
  containers:
  - image: nginx:alpine
    name: container-0
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
