apiVersion: v1
kind: Pod
metadata:
  labels:
    app: configmap
  name: jackson-chen-pod-use-configmap123
spec:
  containers:
    - name: pod-use-configmap
      image: nginx
      env:
        - name: Jackson_Level_Key #value 會放在這裡
          valueFrom:
            configMapKeyRef: #代表要參考哪一組 configmap
              name: jackson-chen-configmap # 那一組 configmap 的名稱
              key: special.how #那一組 configmap有的 key
        - name: Jackson_Type_Key
          valueFrom:
            configMapKeyRef:
              name: jackson-chen-configmap2
              key: log_level
  restartPolicy: Never
