apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod-3
  labels:
    app: pod-3
spec:
  containers:
  - name: pod-3
    image: nginx
  tolerations:
  - key: "check"
    operator: "Equal"
    value: "jackson"
    effect: "NoExecute"
    tolerationSeconds: 3600
