apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: wrre/hello-kubernetes-client:v1
    ports:
    - name: jackson
      containerPort: 80
    volumeMounts:
    - mountPath: /app/healthy
      name: cache-volume
    readinessProbe:
      exec:
        command:
        - cat
        - /app/healthy/test.txt
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      exec:
        command:
        - cat
        - /app/healthy/test.txt
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  initContainers:
  - name: init-jackson-chen-first-container
    image: wrre/hello-kubernetes-client:v1
    command: ['sh', '-c', 'touch /app/healthy/test.txt']
    volumeMounts:
    - mountPath: /app/healthy
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
