#將Secret導出到環境變量中
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-with-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jackson-chen-secret-with-deployment
  template:
    metadata:
      labels:
        app: jackson-chen-secret-with-deployment
    spec:
      containers:
      - name: jackson-chen-secret-with-deployment-c
        image: nginx
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080
        env:
        - name: Test_User
          valueFrom:
            secretKeyRef:
              name: jackson-chen-secret
              key: username
        - name: Test_Pass
          valueFrom:
            secretKeyRef:
              name: jackson-chen-secret
              key: password
