apiVersion: v1
kind: Pod
metadata:
  labels:
    app: secret
  name: jackson-chen-secret
spec:
  containers:
    - name: db
      image: nginx
      volumeMounts:
        - name: jackson-chen-secretsss
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: jackson-chen-secretsss
      secret:
        secretName: jackson-chen-secret #這邊一定要跟 kind:secret 的 名稱一樣
#在container裡面拿到的secret , 他已經幫我們解密了
