apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jackson-chen-helm 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jackson-chen-helm
  template:
    metadata:
      labels:
        app: jackson-chen-helm 
    spec:
      containers:
        - name: jackson-chen-helm 
          image: nginx 
          ports:
            - containerPort: 80
              protocol: TCP
