apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jackson-chen-deployment-set-resource
  name: jackson-chen-deployment-set-resource
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jackson-chen-deployment-specific-node217
  template:
    metadata:
      labels:
        app: jackson-chen-deployment-specific-node217
    spec:
      containers:
      - name: jackson-chen-deployment-specific-node217
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 400m
            memory: 1Gi

